### ISSUE TITLE
Add a task list of guild per realm to fetch.

### ISSUE THREAD

**Issue by KaivoAnastetiks** [KaivoAnastetiks/kronos-wow-guild-fetch#4]
In firebase, there will be a node that lists all the guilds per realm that need to be fetched. This list will then be used as a loop to call guild fetches.

That code should be in lib/app/index.js and with a firebase connection on the tasks node to then instanciate all the other firebase/guildFetch/guildRepo for each guilds.

Once the fetch for a loop is complete, the last time fetched of the scraper must be saved.

- [x] Figure out the null bosskill ID.
- [x] Figure out why not all character's bosskills.
- [x] Figure out why not all character's items.
- [x] Figure out why not items as arrays.
- [x] Add logs for missing data from the server.
- [x] Add support for riding profession.
- [x] Save removed character should remove date added and set a date removed.
